### ISSUE TITLE
Replace Demo image with animated gif

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/unicode-formatter#15]
Possible tools for GIF creation: https://github.com/phw/peek, https://www.cockos.com/licecap/, https://www.screentogif.com/

**Comment by SJellen** [comment]
Let me know if you like this

![demo](https://user-images.githubusercontent.com/51421669/115149386-dc9c3b00-a031-11eb-9551-c90135be6028.gif)

**Comment by SJellen** [comment]
Let me know if you like this
![demo](https://user-images.githubusercontent.com/51421669/115149507-77951500-a032-11eb-8222-b839b704e902.gif)

**Comment by DenverCoder1** [comment]
Hi @SJellen, that looks great! 

I think the second one is more like what I was thinking.

Maybe more of the fonts could be included, though, such as Monospace and one of the Script fonts?

Anyway, it's looking good. Thanks for your help. :+1:

**Comment by SJellen** [comment]
![demo3](https://user-images.githubusercontent.com/51421669/115153512-589f7e80-a044-11eb-94cc-5699b9e65b36.gif)

**Comment by DenverCoder1** [comment]
@SJellen At the start, I think it should have the original text with no modifications and maybe highlight smaller selections? I'd also probably avoid Math Sans since it's almost like normal text and avoid the circle and square fonts and subscript since they can be a bit difficult to read.

The 2nd gif in the first message was pretty much perfect, just it would be nice to have some of the more useful fonts represented.

I like the idea of clicking the eraser at the end, but maybe avoid fonts that can be ambiguous (eg. fonts with no distinction between upper and lowercase) so that the text is the exact same as it started when you click it. It would make a cool loop that way :smile:

**Comment by SJellen** [comment]
heres demo4. 
I tried  to get in as many as I could. The issue is that the longer the video the lower quality the gif.
 **oops,  I just saw your note about the subscript **

![demo4](https://user-images.githubusercontent.com/51421669/115247650-f9e60d80-a0f4-11eb-92dd-4fd060d8fd7a.gif)

**Comment by DenverCoder1** [comment]
@SJellen This is great!

Would you like to make a PR to fix the issue?
