### ISSUE TITLE
[FR] add CLI

### ISSUE THREAD

**Issue by NightMachinary** [DenverCoder1/unicode-formatter#24]
A CLI that reads the text from stdin and converts it to the given 'font' would be good:
```
echo Inverted | unicode-formatter --font Inverted
```

```
pǝʇɹǝʌuI
```

This should be doable with `node`, though the code needs to be refactored into a library first.

**Comment by DenverCoder1** [comment]
Hi @NightMachinary! Thanks for opening the issue!

I'm not sure if that's in the scope of this project at the current time, but it seems like https://github.com/paw-lu/dressup can do what you're thinking of.

Let me know if that solves the issue. :)

**Comment by NightMachinary** [comment]
Thanks! I ended up using ‘mimic’. Feel free to close the issue.
