### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/unicode-formatter#27]
The demo site is currently missing a favicon.

A custom icon could be designed or a fitting free icon could be used. Twemoji is 100% free for use, so an emoji can be taken from there.

**Comment by irahrosete** [comment]
hi, can you assign me to work on this one? thanks.

**Comment by DenverCoder1** [comment]
@irahrosete That would be great, if you have any questions feel free to ask

**Comment by divyanshraj0408** [comment]
any update on the issue?

**Comment by DenverCoder1** [comment]
@irahrosete Do you plan on continuing with this?

If I don't hear anything within a week I'll assume I can assign someone else

**Comment by heySanj** [comment]
Might give this one a crack 😌
