### ISSUE TITLE
special characters (french...)

### ISSUE THREAD

**Issue by frelle** [DenverCoder1/unicode-formatter#28]
Hi, 

Do you know how can I integrate special characters (for example, for french, éèàà ) ? 

thank you

**Comment by DenverCoder1** [comment]
The unicode fonts only support certain symbols so you won't find variations that include those.

You can however try using [Combining Characters](https://en.wikipedia.org/wiki/Combining_character) to add accents to any symbol.

Eg:
```
◌̀ ◌́
```

These links will allow you to copy the accent symbol to your clipboard:

https://unicode-explorer.com/c/0300
https://unicode-explorer.com/c/0301

Then they can be pasted after any character to make it appear above.
