### ISSUE TITLE
Add issue and PR templates

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/unicode-formatter#39]
Add templates for community standards.

These go in the .github folder.

Feel free to take a look at other repos including https://github.com/DenverCoder1/github-readme-youtube-cards/tree/main/.github for examples.

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by DenverCoder1** [comment]
@Vinitvh Sure, go ahead :+1:
